project_id = "isieibfnexlimfujpqma"

[functions.kakao-geocode]
verify_jwt = false

[functions.kakao-reverse-geocode]
verify_jwt = false

[functions.fetch-emergency-rooms]
verify_jwt = false

[functions.fetch-hospitals]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false

[functions.health-analysis]
verify_jwt = false